# Generated by Django 4.2.7 on 2023-11-14 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_hotelcatalog_city_hotelcatalog_house_number_and_more'),
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='hotel_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='catalog.hotelcatalog'),
            preserve_default=False,
        ),
    ]
