# Generated by Django 4.2.7 on 2023-11-14 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_apartment_hotel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='number_of_bathroom',
            field=models.PositiveIntegerField(default=False, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='numer_of_bedrooms',
            field=models.BooleanField(default=False, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
