# Generated by Django 4.2.7 on 2023-11-14 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_apartment_number_of_bathroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='numer_of_bedrooms',
            field=models.BooleanField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
