version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: hotelcatalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - main


  db:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - main


networks:
  main:

volumes:
  db: