# Generated by Django 4.2.6 on 2023-11-06 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_infohotelcatalog_hotelcatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelcatalog',
            name='country',
            field=models.CharField(default=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotelcatalog',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
