# Generated by Django 4.2.7 on 2023-11-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_hotelcatalog_country_alter_hotelcatalog_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelcatalog',
            name='city',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelcatalog',
            name='house_number',
            field=models.CharField(default=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelcatalog',
            name='street',
            field=models.CharField(default=False, max_length=20),
            preserve_default=False,
        ),
    ]
